services:
  - type: web
    name: prateeks-ai-api
    runtime: python3
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: GROQ_API_KEY
        sync: false