services:
  - type: web
    name: prateeks-ai-api
    runtime: python3
    buildCommand: pip install Flask==3.1.1 Flask-CORS==6.0.1 gunicorn==23.0.0 requests==2.32.4
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: GROQ_API_KEY
        sync: false